env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    id: revgen
    binary: revgen
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=gorelease
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
brews:
  - name: revgen
    tap:
      owner: inigolabs
      name: homebrew-tap
    homepage: https://github.com/inigolabs/revgen
    description: Only run go:generate when code changes
    install: |
      bin.install "revgen"
    license: "MIT"